### PR TITLE
feat: allow running on server-side

### PR DESCRIPTION
**Pull request by nha**
Note: I have not ran the tests, since I don't know how to (`lein test` does nothing here).

### CODE REVIEW

**Comment by awkay** [comment]
So, I don't have much of a way to confirm this works. There is a cookbook recipe (the css one) that uses this. Could you at least make sure this works with that?

**Comment by nha** [comment]
Are you talking about https://github.com/untangled-web/untangled-cookbook/tree/develop/recipes/css ? I can have a look.

Also, I would like to know: is there a way to run the tests?

**Comment by awkay** [comment]
It uses Untangled Spec, which renders the tests to the browser. The project isn't set up for CI yet (with doo), so you'd have to start a figwheel build and load index.html on whatever port figwheel comes up on.

something like `lein run -m clojure.main script/figwheel.clj ` should do it, then http://localhost:3449

**Comment by awkay** [comment]
You should be able to convert the tests to cljc and have them work for both client/server. To run the server-side, just use `lein test` (the output is better if you use test-refresh as described in the untangled-spec docs.)

**Comment by awkay** [comment]
Any progress on this @nha ?

**Comment by stephenway** [comment]
@nha I ran tests on your PR branch and ran into some errors. Running `lein test` produces the same.
image

**Comment by awkay** [comment]
@nha I did some quick fixes here:

https://github.com/untangled-web/om-css/tree/nha-feature/server-side

If you'd merge those changes into your branch, then you'll be able to run the clj tests (which are failing) with: 

`lein test-refresh`

The thing that is failing is that the code currently tries to output js objects...which isn't possible on the server-side. Line 127 of the macro needs some work. Probably need to make a helper function that can have a clj and a cljs version, and use it within the macro (you don't want to deal with detecting env inside of the macro).

**Comment by awkay** [comment]
This is looking pretty good. Is it ready @nha ?

**Comment by nha** [comment]
Not good yet, the tests fail and I can't figure out why.
If anyone has a clue/want to fix it I would be grateful, otherwise I will take another stab this weekend.

Thanks for your help on slack by the way :)

**Comment by awkay** [comment]
This was merged via Timo's PR that incorporated this work.

**Comment by nha** [comment]
Nice!
Thanks @TimovanderKamp

**Pull request closed without merging**
